### ISSUE TITLE
Clustering fails

### ISSUE THREAD

**Issue by lbugnon** [jwohlwend/boltz#140]
When running the clustering script with provided fasta throws segmentation fault. I'm running with 256Gb, it does not seem a memory issue. Any thoughts?

```python scripts/process/cluster.py --ccd ../.boltz/ccd.pkl --sequences data/pdb_seqres.txt --outdir clustering
easy-cluster clustering/proteins.fasta clustering/clust_prot clustering/tmp --min-seq-id 0.4 

MMseqs Version:                         16.747c6
Substitution matrix                     aa:blosum62.out,nucl:nucleotide.out
Seed substitution matrix                aa:VTML80.out,nucl:nucleotide.out
Sensitivity                             4
k-mer length                            0
Target search mode                      0
k-score                                 seq:2147483647,prof:2147483647
Alphabet size                           aa:21,nucl:5
Max sequence length                     65535
Max results per query                   20
Split database                          0
Split mode                              2
Split memory limit                      0
Coverage threshold                      0.8
Coverage mode                           0
Compositional bias                      1
Compositional bias                      1
Diagonal scoring                        true
Exact k-mer matching                    0
Mask residues                           1
Mask residues probability               0.9
Mask lower case residues                0
Minimum diagonal score                  15
Selected taxa                       
Include identical seq. id.              false
Spaced k-mers                           1
Preload mode                            0
Pseudo count a                          substitution:1.100,context:1.400
Pseudo count b                          substitution:4.100,context:5.800
Spaced k-mer pattern                
Local temporary path                
Threads                                 72
Compressed                              0
Verbosity                               3
Add backtrace                           false
Alignment mode                          3
Alignment mode                          0
Allow wrapped scoring                   false
E-value threshold                       0.001
Seq. id. threshold                      0.4
Min alignment length                    0
Seq. id. mode                           0
Alternative alignments                  0
Max reject                              2147483647
Max accept                              2147483647
Score bias                              0
Realign hits                            false
Realign score bias                      -0.2
Realign max seqs                        2147483647
Correlation score weight                0
Gap open cost                           aa:11,nucl:5
Gap extension cost                      aa:1,nucl:2
Zdrop                                   40
Rescore mode                            0
Remove hits by seq. id. and coverage    false
Sort results                            0
Cluster mode                            0
Max connected component depth           1000
Similarity type                         2
Weight file name                    
Cluster Weight threshold                0.9
Single step clustering                  false
Cascaded clustering steps               3
Cluster reassign                        false
Remove temporary files                  true
Force restart with latest tmp           false
MPI runner                          
k-mers per sequence                     21
Scale k-mers per sequence               aa:0.000,nucl:0.200
Adjust k-mer length                     false
Shift hash                              67
Include only extendable                 false
Skip repeating k-mers                   false
Database type                           0
Shuffle input database                  true
Createdb mode                           1
Write lookup file                       0
Offset of numeric ids                   0

createdb clustering/proteins.fasta clustering/tmp/6856804258380486242/input --dbtype 0 --shuffle 1 --createdb-mode 1 --write-lookup 0 --id-offset 0 --compressed 0 -v 3 

Shuffle database cannot be combined with --createdb-mode 0
We recompute with --shuffle 0
Converting sequences
Last byte is not a newline. We recompute with --createdb-mode 1
Time for merging to input_h: 0h 0m 0s 0ms
Time for merging to input: 0h 0m 0s 0ms
[165136] 0s 222ms
Time for merging to input_h: 0h 0m 0s 5ms
Time for merging to input: 0h 0m 0s 17ms
Database type: Aminoacid
Time for processing: 0h 0m 0s 261ms
Create directory clustering/tmp/6856804258380486242/clu_tmp
cluster clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu clustering/tmp/6856804258380486242/clu_tmp --max-seqs 20 -c 0.8 --spaced-kmer-mode 1 --alignment-mode 3 -e 0.001 --min-seq-id 0.4 --remove-tmp-files 1 

Set cluster sensitivity to -s 4.000000
Set cluster mode SET COVER
Set cluster iterations to 3
linclust clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/clu_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 72 --compressed 0 -v 3 --cluster-weight-threshold 0.9 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.4 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --alph-size aa:13,nucl:5 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 -k 0 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --rescore-mode 0 --filter-hits 0 --sort-results 0 --remove-tmp-files 1 --force-reuse 0 

kmermatcher clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --alph-size aa:13,nucl:5 --min-seq-id 0.4 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 72 --compressed 0 -v 3 --cluster-weight-threshold 0.9 

kmermatcher clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --alph-size aa:13,nucl:5 --min-seq-id 0.4 --kmer-per-seq 21 --spaced-kmer-mode 1 --kmer-per-seq-scale aa:0.000,nucl:0.200 --adjust-kmer-len 0 --mask 0 --mask-prob 0.9 --mask-lower-case 0 --cov-mode 0 -k 0 -c 0.8 --max-seq-len 65535 --hash-shift 67 --split-memory-limit 0 --include-only-extendable 0 --ignore-multi-kmer 0 --threads 72 --compressed 0 -v 3 --cluster-weight-threshold 0.9 

Database size: 165172 type: Aminoacid
Reduced amino acid alphabet: (A S T) (C) (D B N) (E Q Z) (F Y) (G) (H) (I V) (K R) (L J M) (P) (W) (X) 

Generate k-mers list for 1 split
[=================================================================] 100.00% 165.17K 11s 906ms   
Sort kmer 0h 0m 0s 44ms
Sort by rep. sequence 0h 0m 0s 19ms
Time for fill: 0h 0m 0s 38ms
Time for merging to pref: 0h 0m 0s 0ms
Time for processing: 0h 0m 12s 150ms
rescorediagonal clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_rescore1 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --rescore-mode 0 --wrapped-scoring 0 --filter-hits 0 -e 0.001 -c 0.8 -a 0 --cov-mode 0 --min-seq-id 0.5 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 72 --compressed 0 -v 3 

[=================================================================] 100.00% 165.17K 3s 2ms      
Time for merging to pref_rescore1: 0h 0m 0s 94ms================> ] 97.88% 161.67K eta 0s       
Time for processing: 0h 0m 3s 248ms
clust clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_rescore1 clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pre_clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 72 --compressed 0 -v 3 --cluster-weight-threshold 0.9 

Clustering mode: Set Cover
[=================================================================] 100.00% 165.17K 2s 615ms    
Sort entries
Find missing connections
Found 187092 new connections.
Reconstruct initial order
[=================================================================] 100.00% 165.17K 2s 790ms    
Add missing connections
[=================================================================] 100.00% 165.17K 0s 26ms     

Time for read in: 0h 0m 5s 545ms
Total time: 0h 0m 5s 588ms

Size of the sequence database: 165172
Size of the alignment database: 165172
Number of clusters: 77604

Writing results 0h 0m 0s 34ms
Time for merging to pre_clust: 0h 0m 0s 0ms
Time for processing: 0h 0m 5s 678ms
createsubdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/order_redundancy clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy -v 3 --subdb-mode 1 

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 29ms
createsubdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/order_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_filter1 -v 3 --subdb-mode 1 

Time for merging to pref_filter1: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 60ms
filterdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_filter1 clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_filter2 --filter-file clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/order_redundancy --threads 72 --compressed 0 -v 3 

Filtering using file(s)
[=================================================================] 100.00% 77.60K 2s 20ms     
Time for merging to pref_filter2: 0h 0m 0s 51ms
Time for processing: 0h 0m 2s 170ms
rescorediagonal clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_filter2 clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_rescore2 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --rescore-mode 1 --wrapped-scoring 0 --filter-hits 1 -e 0.001 -c 0.8 -a 0 --cov-mode 0 --min-seq-id 0.4 --min-aln-len 0 --seq-id-mode 0 --add-self-matches 0 --sort-results 0 --db-load-mode 0 --threads 72 --compressed 0 -v 3 

[=================================================================] 100.00% 77.60K 3s 319ms    
Time for merging to pref_rescore2: 0h 0m 0s 51ms=================>] 99.54% 77.25K eta 0s       
Time for processing: 0h 0m 3s 471ms
align clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_rescore2 clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/aln --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 0 --alignment-mode 3 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.001 --min-seq-id 0.4 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0.8 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 72 --compressed 0 -v 3 

Compute score, coverage and sequence identity
Query database size: 77604 type: Aminoacid
Target database size: 77604 type: Aminoacid
Calculation of alignments
[=================================================================] 100.00% 77.60K 0s 719ms    
Time for merging to aln: 0h 0m 0s 22ms
90143 alignments calculated
85855 sequence pairs passed the thresholds (0.952431 of overall calculated)
1.106322 hits per query sequence
Time for processing: 0h 0m 0s 822ms
clust clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/aln clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/clust --cluster-mode 0 --max-iterations 1000 --similarity-type 2 --threads 72 --compressed 0 -v 3 --cluster-weight-threshold 0.9 

Clustering mode: Set Cover
[=================================================================] 100.00% 77.60K 2s 610ms    
Sort entries
Find missing connections
Found 8251 new connections.
Reconstruct initial order
[=================================================================] 100.00% 77.60K 1s 711ms    
Add missing connections
[=================================================================] 100.00% 77.60K 0s 7ms      

Time for read in: 0h 0m 4s 402ms
Total time: 0h 0m 4s 423ms

Size of the sequence database: 77604
Size of the alignment database: 77604
Number of clusters: 71656

Writing results 0h 0m 0s 24ms
Time for merging to clust: 0h 0m 0s 0ms
Time for processing: 0h 0m 4s 494ms
mergeclusters clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/clu_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pre_clust clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/clust --threads 72 --compressed 0 -v 3 

Clustering step 1
[=================================================================] 100.00% 77.60K 1s 611ms    
Clustering step 2
[=================================================================] 100.00% 71.66K 2s 400ms      
Write merged clustering
[=================================================================] 100.00% 165.17K 4s 483ms     
Time for merging to clu_redundancy: 0h 0m 0s 52ms
Time for processing: 0h 0m 4s 580ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_filter1 -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref -v 3 

Time for processing: 0h 0m 0s 2ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_rescore1 -v 3 

Time for processing: 0h 0m 0s 3ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pre_clust -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/input_step_redundancy_h -v 3 

Time for processing: 0h 0m 0s 0ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_filter2 -v 3 

Time for processing: 0h 0m 0s 2ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/pref_rescore2 -v 3 

Time for processing: 0h 0m 0s 2ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/aln -v 3 

Time for processing: 0h 0m 0s 3ms
rmdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/linclust/2113387494741811417/clust -v 3 

Time for processing: 0h 0m 0s 0ms
createsubdb clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/clu_redundancy clustering/tmp/6856804258380486242/input clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/input_step_redundancy -v 3 --subdb-mode 1 

Time for merging to input_step_redundancy: 0h 0m 0s 0ms
Time for processing: 0h 0m 0s 29ms
prefilter clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/input_step_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/input_step_redundancy clustering/tmp/6856804258380486242/clu_tmp/11956452796454511493/pref_step0 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --seed-sub-mat 'aa:VTML80.out,nucl:nucleotide.out' -s 1 -k 0 --target-search-mode 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 20 --split 0 --split-mode 2 --split-memory-limit 0 -c 0.8 --cov-mode 0 --comp-bias-corr 0 --comp-bias-corr-scale 1 --diag-score 0 --exact-kmer-matching 0 --mask 1 --mask-prob 0.9 --mask-lower-case 0 --min-ungapped-score 0 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 72 --compressed 0 -v 3 

Query database size: 71656 type: Aminoacid
Estimated memory consumption: 1G
Target database size: 71656 type: Aminoacid
Index table k-mer threshold: 154 at k-mer size 6 
Index table: counting k-mers
[=================================================================] 100.00% 71.66K 0s 835ms    
Index table: Masked residues: 0
Index table: fill
[=================================================================] 100.00% 71.66K 2s 962ms    
Index statistics
Entries:          8035251
DB size:          534 MB
Avg k-mer size:   0.125551
Top 10 k-mers
    SGVRHM      1728
    LGLKFP      742
    VHFAQS      739
    WNGLGV      729
    TYCVKP      699
    PSSGTY      698
    LGQYNV      697
    YFEVSW      697
    WGGLVS      611
    RQPKEW      610
Time for index table init: 0h 0m 4s 517ms
Process prefiltering step 1 of 1

k-mer similarity threshold: 154
Starting prefiltering scores calculation (step 1 of 1)
Query db start 1 to 71656
Target db start 1 to 71656
Segmentation fault (core dumped)                                  ] 0.00% 1 eta -
Error: Prefilter step 0 died
Error: Search died
Traceback (most recent call last):
  File "/nvme0n1-disk/boltz/scripts/process/cluster.py", line 107, in <module>
    main(args)
  File "/nvme0n1-disk/boltz/scripts/process/cluster.py", line 43, in main
    subprocess.run(
  File "/home/lbugnon/.conda/envs/boltz/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mmseqs easy-cluster clustering/proteins.fasta clustering/clust_prot clustering/tmp --min-seq-id 0.4' returned non-zero exit status 1.```

**Comment by shenoynikhil** [comment]
I have also faced a similar issue. Haven't found time to debug it though.

**Comment by jwohlwend** [comment]
I swear this was working before. I don't know what's causing it. It works when I pick the first 1000 sequences.. I'll try to reach out to the mmseqs people to see if they have an idea.

**Comment by shenoynikhil** [comment]
You're right, I tried to do it on a smaller list of sequences (<100) and it seems to work.

**Comment by jwohlwend** [comment]
Alright, after some lengthy debugging I found that this seems to be due to short proteins (less than 10 AA). I now separate these out and assign each to a unique cluster, similar to how rna/dna are handled. I pushed the fix!
