### ISSUE TITLE
atom_idx_map starting from 0?

### ISSUE THREAD

**Issue by YumizSui** [jwohlwend/boltz#26]
When attempting to predict the structure of a cyclic peptide, I encountered an error related to atom indexing. 

The following input was given and an error occurred.
```
version: 1
sequences:
  - protein:
      id: [A]
      sequence: ACDEFGH
      msa: test.a3m # only 1 sequence file
constraints:
    - bond:
        atom1: [A, 1, "N"]
        atom2: [A, 7, "C"]

```
```
Processing input data.
  0%|                                                                                                                | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/path/to/boltz/bin/boltz", line 8, in <module>
    sys.exit(cli())
  File "/path/to/boltz/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/path/to/boltz/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/path/to/boltz/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/path/to/boltz/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/path/to/boltz/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/path/to/boltz/lib/python3.9/site-packages/boltz/main.py", line 346, in predict
    processed = process_inputs(data, out_dir, ccd)
  File "/path/to/boltz/lib/python3.9/site-packages/boltz/main.py", line 179, in process_inputs
    target = parse_yaml(path, ccd)
  File "/path/to/boltz/lib/python3.9/site-packages/boltz/data/parse/yaml.py", line 57, in parse_yaml
    return parse_boltz_schema(name, data, ccd)
  File "/path/to/boltz/lib/python3.9/site-packages/boltz/data/parse/schema.py", line 737, in parse_boltz_schema
    c2, r2, a2 = atom_idx_map[tuple(constraint["bond"]["atom2"])]
KeyError: ('A', 7, 'C')
```

Debug output revealed that atom_idx_map is zero-based, which appears to be causing the issue.
```
atom_idx_map {('A', 0, 'N'): (0, 0, 0), ('A', 0, 'CA'): (0, 0, 1), ('A', 0, 'C'): (0, 0, 2), ('A', 0, 'O'): (0, 0, 3), ('A', 0, 'CB'): (0, 0, 4), ('A', 1, 'N'): (0, 1, 5), ('A', 1, 'CA'): (0, 1, 6), ('A', 1, 'C'): (0, 1, 7), ('A', 1, 'O'): (0, 1, 8), ('A', 1, 'CB'): (0, 1, 9), ('A', 1, 'SG'): (0, 1, 10), ('A', 2, 'N'): (0, 2, 11), ('A', 2, 'CA'): (0, 2, 12), ('A', 2, 'C'): (0, 2, 13), ('A', 2, 'O'): (0, 2, 14), ('A', 2, 'CB'): (0, 2, 15), ('A', 2, 'CG'): (0, 2, 16), ('A', 2, 'OD1'): (0, 2, 17), ('A', 2, 'OD2'): (0, 2, 18), ('A', 3, 'N'): (0, 3, 19), ('A', 3, 'CA'): (0, 3, 20), ('A', 3, 'C'): (0, 3, 21), ('A', 3, 'O'): (0, 3, 22), ('A', 3, 'CB'): (0, 3, 23), ('A', 3, 'CG'): (0, 3, 24), ('A', 3, 'CD'): (0, 3, 25), ('A', 3, 'OE1'): (0, 3, 26), ('A', 3, 'OE2'): (0, 3, 27), ('A', 4, 'N'): (0, 4, 28), ('A', 4, 'CA'): (0, 4, 29), ('A', 4, 'C'): (0, 4, 30), ('A', 4, 'O'): (0, 4, 31), ('A', 4, 'CB'): (0, 4, 32), ('A', 4, 'CG'): (0, 4, 33), ('A', 4, 'CD1'): (0, 4, 34), ('A', 4, 'CD2'): (0, 4, 35), ('A', 4, 'CE1'): (0, 4, 36), ('A', 4, 'CE2'): (0, 4, 37), ('A', 4, 'CZ'): (0, 4, 38), ('A', 5, 'N'): (0, 5, 39), ('A', 5, 'CA'): (0, 5, 40), ('A', 5, 'C'): (0, 5, 41), ('A', 5, 'O'): (0, 5, 42), ('A', 6, 'N'): (0, 6, 43), ('A', 6, 'CA'): (0, 6, 44), ('A', 6, 'C'): (0, 6, 45), ('A', 6, 'O'): (0, 6, 46), ('A', 6, 'CB'): (0, 6, 47), ('A', 6, 'CG'): (0, 6, 48), ('A', 6, 'ND1'): (0, 6, 49), ('A', 6, 'CD2'): (0, 6, 50), ('A', 6, 'CE1'): (0, 6, 51), ('A', 6, 'NE2'): (0, 6, 52)}
```
The atom_idx_map is currently zero-based, which may be inconsistent with other parts of the system.

**Comment by jwohlwend** [comment]
That's a good catch. I just pushed a fix to the main branch. Will make a new pypi release soon too.
