### ISSUE TITLE
"pickle data was truncated" error

### ISSUE THREAD

**Issue by Geoff-CQW** [jwohlwend/boltz#44]
Hi everyone,

Thanks for your excellent work on this great model!

I've been trying to run the model but I get an unpickling error. The full error is:

Running predictions for 1 structure
Processing input data.
Traceback (most recent call last):
  File "/root/miniforge3/envs/boltz2/bin/boltz", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/boltz/main.py", line 446, in predict
    process_inputs(
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/lightning_utilities/core/rank_zero.py", line 42, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniforge3/envs/boltz2/lib/python3.12/site-packages/boltz/main.py", line 233, in process_inputs
    ccd = pickle.load(file)  # noqa: S301
          ^^^^^^^^^^^^^^^^^

**Comment by Geoff-CQW** [comment]
I checked through my files and realize the issue was because the weights were not downloaded properly. Closing the issue. Thanks again for your work!
