### ISSUE TITLE
0.3.0 fails where 0.2.1 worked yesterday

### ISSUE THREAD

**Issue by vaclavhanzl** [jwohlwend/boltz#66]
Yesterday it worked great for me till cca. 614 tokens (huge thanks to the developers!). The only issue was some package version mismatch which I resolved easily by forcing python 3.12, installing like this:
```
hanzl@blackbox:~$ mamba create -n boltz
(boltz) hanzl@blackbox:~$ mamba install pip
(boltz) hanzl@blackbox:~$ mamba install python==3.12
(boltz) hanzl@blackbox:~$ pip install boltz
```

Today I repeated the install (in a different mamba environment) to get the new version 0.3.0, however instead of longer predictions, I am not able to repeat my yesterday 614 token one:

```
Predicting: |                                                                                                                                           | 0/? [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/hanzl/miniforge3/envs/boltz.3/bin/boltz", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/boltz/main.py", line 614, in predict
    trainer.predict(
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 858, in predict
    return call._call_and_handle_interrupt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 897, in _predict_impl
    results = self._run(model, ckpt_path=ckpt_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 981, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1020, in _run_stage
    return self.predict_loop.run()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/loops/utilities.py", line 178, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/loops/prediction_loop.py", line 121, in run
    batch, batch_idx, dataloader_idx = next(data_fetcher)
                                       ^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/loops/fetchers.py", line 133, in __next__
    batch = super().__next__()
            ^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/loops/fetchers.py", line 60, in __next__
    batch = next(self.iterator)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/utilities/combined_loader.py", line 341, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/pytorch_lightning/utilities/combined_loader.py", line 142, in __next__
    out = next(self.iterators[0])
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1491, in _process_data
    data.reraise()
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/torch/_utils.py", line 715, in reraise
    raise exception
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 41, in do_one_step
    data = pin_memory(data, device)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 75, in pin_memory
    {k: pin_memory(sample, device) for k, sample in data.items()}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hanzl/miniforge3/envs/boltz.3/lib/python3.12/site-packages/torch/utils/data/_utils/pin_memory.py", line 64, in pin_memory
    return data.pin_memory(device)
           ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by vaclavhanzl** [comment]
Sorry, re-testing with the yesterday version now fails, too. Something is broken on my system but maybe not the new Boltz. Closing this for now and investigating more.
