### ISSUE TITLE
Fresh install leads to broken CLI in both python 3.9 and 3.10

### ISSUE THREAD

**Issue by noahharrison64** [jwohlwend/boltz#68]
Have tried installing boltz locally and reaching the same error each time I try and run boltz CLI.

Install commands:
```
conda create -n new_boltz_env python=3.9 -y 
conda activate new_boltz_env 
pip install boltz # or install via git clone
```

Leads to:
```
Traceback (most recent call last):
  File "/root/miniforge3/envs/new_boltz_env/bin/boltz", line 5, in <module>
    from boltz.main import cli
  File "/root/boltz/src/boltz/main.py", line 8, in <module>
    import torch
  File "/root/miniforge3/envs/new_boltz_env/lib/python3.9/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /root/miniforge3/envs/new_boltz_env/lib/python3.9/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```

This is the case for both py3.9 and 3.10.
Running
```NVIDIA-SMI 535.154.05             Driver Version: 535.154.05   CUDA Version: 12.2 ```

Any advice here would be appreciated!

**Comment by noahharrison64** [comment]
Fixed by installing pytorch first followed by boltz
```mamba install pytorch torchvision torchaudio pytorch-cuda=12.2 -c pytorch -c nvidia```
