### ISSUE TITLE
UnboundLocalError: local variable 'target' referenced before assignment

### ISSUE THREAD

**Issue by Evert-Homan** [jwohlwend/boltz#7]
Hi,

I installed boltz using

`pip install boltz`

All goes well, no errors.

```
.local/bin/boltz --help
Usage: boltz [OPTIONS] COMMAND [ARGS]...

  Boltz1.

Options:
  --help  Show this message and exit.

Commands:
  predict  Run predictions with Boltz-1.
```
So far so good. Then:

```
.local/bin/boltz predict mthfd1l.fas 
Downloading data and model to /home/evehom/.boltz. You may change this by setting the --cache flag.
Checking input data.
Processing input data.
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/evehom/.local/bin/boltz", line 8, in <module>
    sys.exit(cli())
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/evehom/.local/lib/python3.10/site-packages/boltz/main.py", line 346, in predict
    processed = process_inputs(data, out_dir, ccd)
  File "/home/evehom/.local/lib/python3.10/site-packages/boltz/main.py", line 182, in process_inputs
    records.append(target.record)
UnboundLocalError: local variable 'target' referenced before assignment
```

Please advise. Thanks/Evert

**Comment by Evert-Homan** [comment]
Renaming fas to fasta gives me a different error (with only 1 fasta file in this folder):

```
.local/bin/boltz predict P00374.fasta
Downloading data and model to /home/evehom/.boltz. You may change this by setting the --cache flag.
Checking input data.
Processing input data.
  0%|                                                     | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/evehom/.local/bin/boltz", line 8, in <module>
    sys.exit(cli())
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/evehom/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/evehom/.local/lib/python3.10/site-packages/boltz/main.py", line 346, in predict
    processed = process_inputs(data, out_dir, ccd)
  File "/home/evehom/.local/lib/python3.10/site-packages/boltz/main.py", line 177, in process_inputs
    target = parse_fasta(path, ccd)
  File "/home/evehom/.local/lib/python3.10/site-packages/boltz/data/parse/fasta.py", line 55, in parse_fasta
    raise ValueError(msg)
ValueError: Invalid entity type: P00374
```

The fasta file comes directly from UniProt, I copy it from there and paste it into a local file using nano

**Comment by jwohlwend** [comment]
@Evert-Homan our fasta format requires a few things to be specified in the fasta headers. See the instructions [here](https://github.com/jwohlwend/boltz/blob/main/docs/prediction.md)

Let me know if you run into other issues. I’ll also add some logic so we don’t fail on .fas extensions!

**Comment by jwohlwend** [comment]
@Evert-Homan Let me know if you were able to get things going!

**Comment by jwohlwend** [comment]
Closing this for now!

**Comment by Evert-Homan** [comment]
Hi, just to let you know that the latest version works fine with a fasta file and using the --use_msa_server option. Very straightforward to use in this way and fast too, just about 2 minutes to generate a model on an RTX3060 GPU.

Thanks for making this tool available/Evert
