### ISSUE TITLE
RuntimeError: PytorchStreamReader failed

### ISSUE THREAD

**Issue by varunmc92** [jwohlwend/boltz#77]
My company's IT team installed boltz-1 on our HPC system and I tried running it to predict a 2 chain protein multimer complex structure. I am getting the error shown below. I am sure the fasta files have the correct format and the msa folders are being created too. Any help with this error is much appreciated.
Thanks 

boltz predict test.fasta --use_msa_server
Checking input data.
Running predictions for 1 structure
Processing input data.
  0%|                                                                                                                                                            | 0/1 [00:00<?, ?it/s]
Generating MSA for test.fasta with 2 protein entities.
COMPLETE: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [elapsed: 00:01 remaining: 00:00]
COMPLETE: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 300/300 [elapsed: 00:01 remaining: 00:00]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.17s/it]
Traceback (most recent call last):
  File "/apps/software/boltz1/0.3.0/bin/boltz", line 8, in <module>
    sys.exit(cli())
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/apps/software/boltz1/0.3.0/src/boltz/src/boltz/main.py", line 587, in predict
    model_module: Boltz1 = Boltz1.load_from_checkpoint(
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/pytorch_lightning/utilities/model_helpers.py", line 125, in wrapper
    return self.method(cls, *args, **kwargs)
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1582, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 63, in _load_from_checkpoint
    checkpoint = pl_load(checkpoint_path, map_location=map_location)
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/lightning_fabric/utilities/cloud_io.py", line 60, in _load
    return torch.load(
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/torch/serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/apps/software/boltz1/conda/envs/boltz1/lib/python3.9/site-packages/torch/serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by varunmc92** [comment]
It worked. Thanks
