### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by johnnytam100** [jwohlwend/boltz#82]
Hi @jwohlwend Great work! Becoming something big.
Do you know the potential reason for No module named 'torch._six'?

```
(boltz_AF3) me@server:/data/123456/test/test_boltz-AF3/boltz$ boltz predict test.fasta --use_msa_server
Traceback (most recent call last):
  File "/data/123456/test/test_localcolabfold/localcolabfold/colabfold-conda/bin/boltz", line 5, in <module>
    from boltz.main import cli
  File "/data/123456/test/test_boltz-AF3/boltz/src/boltz/main.py", line 23, in <module>
    from boltz.model.model import Boltz1
  File "/data/123456/test/test_boltz-AF3/boltz/src/boltz/model/model.py", line 27, in <module>
    from boltz.model.modules.confidence import ConfidenceModule
  File "/data/123456/test/test_boltz-AF3/boltz/src/boltz/model/modules/confidence.py", line 12, in <module>
    from boltz.model.modules.trunk import (
  File "/data/123456/test/test_boltz-AF3/boltz/src/boltz/model/modules/trunk.py", line 13, in <module>
    from boltz.model.layers.triangular_attention.attention import (
  File "/data/123456/test/test_boltz-AF3/boltz/src/boltz/model/layers/triangular_attention/attention.py", line 22, in <module>
    from boltz.model.layers.triangular_attention.primitives import (
  File "/data/123456/test/test_boltz-AF3/boltz/src/boltz/model/layers/triangular_attention/primitives.py", line 30, in <module>
    and importlib.util.find_spec("deepspeed.ops.deepspeed4science") is not None
  File "/data/123456/test/test_localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/importlib/util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File "/data/123456/test/test_localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/deepspeed/__init__.py", line 16, in <module>
    from .runtime.engine import DeepSpeedEngine, DeepSpeedOptimizerCallable, DeepSpeedSchedulerCallable
  File "/data/123456/test/test_localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 24, in <module>
    from deepspeed.runtime.utils import see_memory_usage, get_ma_status, DummyOptim
  File "/data/123456/test/test_localcolabfold/localcolabfold/colabfold-conda/lib/python3.10/site-packages/deepspeed/runtime/utils.py", line 18, in <module>
    from torch._six import inf
ModuleNotFoundError: No module named 'torch._six'

```

**Comment by jwohlwend** [comment]
Probably happens because you have an older deepspeed installed (note that deepspeed is not a requirement for boltz). I would recommend that you install boltz in a fresh environment. You can also try upgrading deepspeed and see if that helps.

**Comment by johnnytam100** [comment]
Hi @jwohlwend , thanks for the comment and I confirmed it's a problem of my env.
